### ISSUE TITLE
Storing custom type

### ISSUE THREAD

**Issue by genmeblog** [jackrusher/spicerack#11]
Do you know any way to store objects created by `deftype` or `defrecord`? (deftype with `java.io.Serializable` interface).

**Comment by genmeblog** [comment]
Looks like `assoc!` works but reading throws: `java.lang.ClassNotFoundException`

**Comment by jackrusher** [comment]
Check out issue #3 for some background. I have so far mostly seen this when there's an anonymous function in the structure being serialized, for reasons mentioned in #3. What does the `type`/`record` look like?

**Comment by genmeblog** [comment]
Looks like the same issue. I plan to store sequence of Vec4 type from `fastmath`, however they are currently not Serializable. But I tested the following:

```clojure
(deftype Vec [^double x ^double  y]
  java.io.Serializable)
```

**Comment by genmeblog** [comment]
It's not a must actually, I can store sequences of strings or clojure vectors.
