### ISSUE TITLE
database as a resource in jar

### ISSUE THREAD

**Issue by genmeblog** [jackrusher/spicerack#12]
The last concert before I go further. `spicerack` seems to work with the file.  What if I want to include read-only database in the library bundled in the jar. Such files are later accessible via resource url. How to make it here?

**Comment by jackrusher** [comment]
I haven't tested this, but you _should_ be able to use `clojure.java.io/resource` on the file in your jar and then call `(.toURI thing-returned-by-resource)` to get a URI you can pass as the filename to `open-database`. Let me know if that works for you!

**Comment by genmeblog** [comment]
Not that easy... I've created simple project with test.db in resources. When I use it from another library, I'm getting an exception.
When called from the `palettes` library - everything works fine (since resource is a file outside `jar`).

```clojure
(p/get-uri "test.db")
;; => #object[java.net.URI 0x1506913f "jar:file:/home/xxx/.m2/repository/palettes/palettes/0.1.0-SNAPSHOT/palettes-0.1.0-SNAPSHOT.jar!/test.db"]

(p/get-data)

1. Unhandled java.lang.IllegalArgumentException
   Not a file:
   jar:file:/home/xxx/.m2/repository/palettes/palettes/0.1.0-SNAPSHOT/palettes-0.1.0-SNAPSHOT.jar!/test.db

                    io.clj:   61  clojure.java.io/fn
                    io.clj:   44  clojure.java.io/fn
                    io.clj:   35  clojure.java.io/fn/G
                    io.clj:   67  clojure.java.io/fn
                    io.clj:   44  clojure.java.io/fn
                    io.clj:   35  clojure.java.io/fn/G
                  core.clj:   46  spicerack.core/open-database
                  core.clj:   35  spicerack.core/open-database
               RestFn.java:  439  clojure.lang.RestFn/invoke
             spicerack.clj:   18  palettes.spicerack/get-database
             spicerack.clj:   16  palettes.spicerack/get-database
             spicerack.clj:   26  palettes.spicerack/get-data
             spicerack.clj:   24  palettes.spicerack/get-data
```

Content of the `p` namespace:

```clojure
(ns palettes.spicerack
  (:require [spicerack.core :as sr]
            [clojure.java.io :as io]))

(defn assoc-data
  []
  (with-open [db (sr/open-database "resources/test.db")]
    (let [abcs (sr/open-hashmap db "test")]
      (sr/assoc! abcs :a/b (list [1.2 3.4 5.4 3.4]
                                 [2 122 222 222])))))

(defn get-uri
  [filename]
  (.toURI (io/resource filename)))

(defn get-database
  [filename]
  (sr/open-database (get-uri filename) :read-only? true))

(defn get-hashmap
  [db name]
  (sr/open-hashmap db name))

(defn get-data
  []
  (with-open [db (get-database "test.db")]
    (let [abcs (get-hashmap db "test")]
      (get abcs :a/b))))
```

**Comment by genmeblog** [comment]
```clojure
(io/file (.toURI (io/resource "test.db")))

1. Unhandled java.lang.IllegalArgumentException
   Not a file:
   jar:file:/home/xxx/.m2/repository/palettes/palettes/0.1.0-SNAPSHOT/palettes-0.1.0-SNAPSHOT.jar!/test.db
```

Also this: https://stackoverflow.com/questions/20389255/reading-a-resource-file-from-within-jar

I don't see the way to bundle mapdb file into jar and use it via the library :/

**Comment by jackrusher** [comment]
Thinking about it a bit more, that MapDB is using `mmap` under the covers probably means that it needs a real file as the backing store for the DB. After reading the thread on what you're trying to do, this seems like a lot of work to avoid just using an EDN file given that it's only a little read-only data...?

**Comment by genmeblog** [comment]
That's true :) I thought I could pack all palettes into mapdb (or other storage) file and read it when necessary. My current implementation wraps reading into `delay` and load EDNs for first call. It takes about 1-2s now to read all of that stuff. It looked that moving to the storage wasn't big deal but it's not that easy.
Possibly I will stay with EDNs, maybe chunked.

**Comment by jackrusher** [comment]
Good luck and have fun! Hopefully you'll eventually need big off-heap data structures and spicerack will be able to help you. :)
